### ISSUE TITLE
No module named '_gdal_array'

### ISSUE THREAD

**Issue by pzuniga** [dfguerrerom/sepal_smfm_biota#42] opened 2022-10-18 03:28 UTC
Dear Researchers,

In the "Process" frame, clicking "GET OUTPUTS" gives the message "No module named '_gdal_array'" and cannot "DISPLAY OUTPUTS".

Thanks you

kind regards

Pablo

![image](https://user-images.githubusercontent.com/106708017/196328871-a9db22d0-fed8-4ba1-ba40-2aebbf6b2986.png)

**Comment by dfguerrerom** [comment] 2022-10-19 06:52
@pzuniga, the problem is related to a `gdal` cached wheel being installed in our virtual environment, we are working to find a prompt solution. Thanks for reporting.

**Comment by dfguerrerom** [comment] 2022-10-24 15:09
Some findings here:
- the reported error was related to the `gdal` installation in the `biota UI venv`:
     - biota package is using `gdal.Open.ds.ReadAsArray()()` method to open and return images as Numpy arrays (check https://github.com/OSGeo/gdal/tree/master/swig/python#numpy). 
     - the array support is only installed by python gdal binding if Numpy is installed before, the installation will check if it is installed, if not, it will skip the array support.
     - there is no way to change the package installation order in this repo since  [SEPAL deals with this](https://github.com/openforis/sepal/blob/111e148a33dda94505308071934e1d3ed4f6934f/modules/app-manager/update-app.sh#L68).
     - pip doesn't ensure that the installation order in `requirements.txt` is the same order as the packages are listed.
     - adding `gdal[numpy]` `extra_require` doesn't work in gdal==3.4.3. There is a patched version that does this https://github.com/OSGeo/gdal/issues/2158.

To give a prompt I've decided to modify our forked version of biota and use `rasterio` to open images and return the Numpy array, it's been done here https://github.com/dfguerrerom/biota/commit/64286f4f627082135d5445cddf257a16be082b9b.

**Comment by dfguerrerom** [comment] 2022-10-25 07:32
@pzuniga I'm closing this since was fixed with https://github.com/dfguerrerom/biota/commit/64286f4f627082135d5445cddf257a16be082b9b.

**Closed as completed by dfguerrerom** 2022-10-25 07:32 UTC
